version: "3"

services:
  cloud-config-server:
    image: "registro-contable/auth-service:${TAG}"
    container_name: auth-service
    environment:
      - spring.cloud.config.profile=development
      - spring.cloud.config.uri=http://192.168.1.5:8888