gcp:
  credentials:
    filePath: D:\Projects\registro_contable\auth-service\keyfile.json

config:
  security:
    oauth:
      jwt:
        key: abniuft238iq7rgbq73862rt

#logging:
#  level:
#    ROOT: DEBUG